export function buildSidebarProps({
    savedTopics,
    savedReports,
    deleteSavedTopicEntry,
    isSyncing,
    savedError,
    collections,
    quickTopicInputValue,
    setQuickTopicInputValue,
    handleQuickTopicSubmit,
    handleTopicRecall,
    handleForgetReport,
    handleReportOpen,
    handleReset,
    handleGeneratingReportSelect,
    handleOpenCourses,
    handleOpenExplorer,
    activePage,
    useCollectionsFeature,
    handleOpenSettings,
    generatingReport,
}) {
    return {
        savedTopics,
        savedReports,
        generatingReport,
        onGeneratingReportSelect: handleGeneratingReportSelect,
        handleTopicRecall,
        handleTopicRemove: deleteSavedTopicEntry,
        handleReportRemove: handleForgetReport,
        quickTopicInputValue,
        setQuickTopicInputValue,
        handleQuickTopicSubmit,
        onOpenSettings: handleOpenSettings,
        onOpenCourses: handleOpenCourses,
        onOpenExplorer: handleOpenExplorer,
        activePage,
        onReportSelect: handleReportOpen,
        onResetExplore: handleReset,
        isSyncing,
        savedError,
        useCollections: useCollectionsFeature,
        collections: collections.collections,
        expandedCollections: collections.expandedCollections,
        isCreatingCollection: collections.isCreating,
        newCollectionName: collections.newCollectionName,
        editingCollectionId: collections.editingCollectionId,
        onToggleCollectionExpanded: collections.toggleCollectionExpanded,
        onCreateCollection: collections.handleCreateCollection,
        onUpdateCollection: collections.handleUpdateCollection,
        onDeleteCollection: collections.handleDeleteCollection,
        onStartCreatingCollection: collections.startCreating,
        onCancelCreatingCollection: collections.cancelCreating,
        onStartEditingCollection: collections.startEditing,
        onCancelEditingCollection: collections.cancelEditing,
        onNewCollectionNameChange: collections.setNewCollectionName,
        onMoveTopicToCollection: collections.handleMoveTopicToCollection,
    };
}

export function buildTopicViewProps({
    topicViewController,
    modelSelectionProps,
    mainViewState,
    sectionCount,
    setSectionCount,
    isRunning,
}) {
    return {
        isOpen: mainViewState.isTopicViewOpen,
        topic: topicViewController.activeTopic,
        isEditing: topicViewController.isTopicEditing,
        draft: topicViewController.draftTopic,
        setDraft: topicViewController.setDraftTopic,
        isSaved: mainViewState.isTopicSaved,
        suggestions: topicViewController.topicSuggestions,
        suggestionsLoading: topicViewController.suggestionsLoading,
        selectedSuggestions: topicViewController.selectedSuggestions,
        selectMode: topicViewController.selectMode,
        selectToggleRef: topicViewController.selectToggleRef,
        suggestionsRef: topicViewController.suggestionsRef,
        isRunning,
        ...modelSelectionProps,
        handlers: {
            startEditing: topicViewController.startTopicEditing,
            cancelEditing: topicViewController.cancelTopicEditing,
            commitEditing: topicViewController.commitTopicEdit,
            handleEditSubmit: topicViewController.handleTopicEditSubmit,
            handleEditBlur: topicViewController.handleTopicEditBlur,
            handleEditKeyDown: topicViewController.handleTopicEditKeyDown,
            handleTitleKeyDown: topicViewController.handleTopicTitleKeyDown,
            handleSave: topicViewController.handleTopicViewSave,
            handleGenerate: topicViewController.generateTopicReport,
            handleClose: topicViewController.closeTopicView,
            handleOpenTopic: topicViewController.handleOpenTopic,
            handleToggleSuggestion: topicViewController.handleSuggestionToggle,
            handleSaveSelectedSuggestions: topicViewController.handleSaveSelectedSuggestions,
            handleRefreshSuggestions: topicViewController.handleRefreshSuggestions,
            handleToggleSelectMode: topicViewController.handleToggleTopicSelectMode,
            sectionCount,
            setSectionCount,
        },
        editorRef: topicViewController.titleEditorRef,
        avoidTopics: topicViewController.avoidTopics,
        setAvoidTopics: topicViewController.setAvoidTopics,
        includeTopics: topicViewController.includeTopics,
        setIncludeTopics: topicViewController.setIncludeTopics,
    };
}

export function buildMainProps({
    activePage,
    courses,
    coursesGenerationProgress,
    mainViewState,
    exploreSuggestions,
    topicViewProps,
    reportViewProps,
    chatPaneProps,
    outlineFormProps,
    chat,
    navigation,
}) {
    return {
        chatPaneClassName: mainViewState.chatPaneClassName,
        isCoursesPage: activePage === 'courses',
        coursesProps: {
            courses: courses.courses,
            onAddCourse: courses.addCourse,
            onDeleteCourse: courses.deleteCourse,
            onDeleteModule: courses.deleteModuleFromCourse,
            onDeleteTopic: courses.deleteTopicFromModule,
            onToggleModule: courses.toggleModule,
            onToggleTopic: courses.toggleTopic,
            onAddTopicToModule: courses.addTopicToModule,
            onAddModuleToCourse: courses.addModuleToCourse,
            onGenerateTopicReport: navigation.handleGenerateTopicFromCourses,
            onGenerateModuleReports: navigation.handleGenerateModuleFromCourses,
            onGenerateCourseReports: navigation.handleGenerateCourseFromCourses,
            onCancelGeneration: chat.stopGeneration,
            generationProgress: coursesGenerationProgress,
            isRunning: chat.isRunning,
        },
        shouldShowExplore: mainViewState.shouldShowExplore,
        exploreProps: {
            suggestions: exploreSuggestions.suggestions,
            isLoading: exploreSuggestions.isLoading,
            selectedSuggestions: exploreSuggestions.selectedSuggestions,
            isSelectMode: exploreSuggestions.isSelectMode,
            selectToggleRef: exploreSuggestions.selectToggleRef,
            suggestionsRef: exploreSuggestions.suggestionsRef,
            onRefresh: exploreSuggestions.refreshSuggestions,
            onToggleSuggestion: exploreSuggestions.toggleSuggestionSelection,
            onToggleSelectMode: exploreSuggestions.toggleSelectMode,
            handleOpenTopic: navigation.handleOpenTopic,
        },
        topicViewProps,
        reportViewProps,
        chatPaneProps,
        outlineFormProps,
    };
}
